/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockQuestions: typeof import('./src/components/question/BlockQuestions.vue')['default']
    BlockResult: typeof import('./src/components/result/BlockResult.vue')['default']
    Button: typeof import('primevue/button')['default']
    ItemQuestions: typeof import('./src/components/question/ItemQuestions.vue')['default']
    ItemResult: typeof import('./src/components/result/ItemResult.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UButton: typeof import('./src/components/ui/UButton.vue')['default']
  }
}
